syntax = "proto3";
package device;
option go_package = "github.com/sharma-ayush1999/rpc/proto/device";

import "google/protobuf/timestamp.proto";

message Device {
    string id = 1;
    string name = 2;
    string status = 3; // "online" | "offline" | "error"
    google.protobuf.Timestamp last_seen = 4;
}
message GetDeviceStatusRequest { string device_id = 1; }
message GetDeviceStatusResponse { Device device = 1; }

message StreamDeviceEventsRequest { string device_id = 1;}
message DeviceEvent {
    string device_id = 1;
    string event_type = 2;
    string message = 3;
    google.protobuf.Timestamp occurred_at = 4;
}

service DeviceService {
    rpc GetDeviceStatus(GetDeviceStatusRequest) returns (GetDeviceStatusResponse);
    rpc StreamDeviceEvents(StreamDeviceEventsRequest) returns (stream DeviceEvent);
}